riegl_vz_node:
  ros__parameters:
    hostname: "H2222222"
    ssh_user: "user"
    ssh_password: "user"
    working_dir: "/tmp/.ros_riegl_vz"
    project_name: ""
    stor_media: 2
    meas_program: 3
    scan_pattern: [30.0,130.0,0.1,0.0,360.0,0.1]
    scan_filter: ""
    scan_publish: True
    scan_register: True
