riegl_vz_node:
  ros__parameters:
    hostname: "H2222222"
    ssh_user: "user"
    ssh_password: "user"
    working_dir: "/tmp/ros_riegl_vz"
    project_name: ""
    storage_media: 0
    meas_program: 3
    scan_pattern_name: ""
    scan_pattern: [30.0,130.0,0.1,0.0,360.0,0.5]
    scan_publish: True
    scan_publish_filter: ""
    scan_publish_lod: 8
    scan_register: True
    pose_publish: True
    voxel_publish: False
    reflector_search: False
    reflector_search_models: "RIEGL flat reflector 50 mm"
    reflector_search_limits: [1.0,100.0]
    control_points_csv_file: ""
    control_points_coord_system: "EPSG::4978"
    image_capture: 0
    image_capture_mode: 1
    image_capture_overlap: 25
    robot_relative_pose: False
    robot_scanner_mounting_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    robot_project_frame_id: ""
    robot_scanner_project_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
