riegl_vz_node:
  ros__parameters:
    hostname: "H2222222"
    ssh_user: "user"
    ssh_password: "user"
    working_dir: "/tmp/ros_riegl_vz"
    storage_media: 0
    meas_program: 3
    scan_pattern: [30.0,130.0,0.04,0.0,360.0,0.5]
    scan_publish: True
    scan_publish_filter: ""
    scan_publish_lod: 0
    scan_register: True
